name: hypurr-bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          clean: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.13"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m playwright install --with-deps chromium   # ⬅️ ОБЯЗАТЕЛЬНО

      - name: Run scraper
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          TARGET_URL:         ${{ secrets.TARGET_URL }}
          METHOD_KEYWORD:     "order"
          MAX_SEND:           "10"
        run: python scraper.py

      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: |
            page.html
            page.png
          if-no-files-found: ignore
          retention-days: 1