name: hypurr-bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-24.04   # ОБЯЗАТЕЛЬНО 24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          clean: true

      # Покажем реальную ОС/GLIBC в логах
      - name: Show OS info
        run: |
          uname -a
          cat /etc/os-release || true
          ldd --version || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.13"
          cache: "pip"

      - name: Debug Python
        run: |
          python --version
          which python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run scraper
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TARGET_URL: ${{ secrets.TARGET_URL }}   # https://hypurrscan.io/address/0xc2a30212a8ddac9e123944d6e29faddce994e5f2
          METHOD_KEYWORD: "order"                     # под ваш столбец Method
          MAX_SEND: "10"
        run: python scraper.py


      - name: Commit seen.json if changed
        run: |
          if ! git diff --quiet --exit-code -- seen.json; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add seen.json
            git commit -m "update seen.json"
            git push
          fi
